#!/bin/bash
# Script to auto map Monoprice 10x6.25 in Tablet on detection
# ------------------------------------------------------------
# If you intend to use this script, you may wish to modify it
# For use with your personal system configuration and hardware

MONITOR="HDMI-0"
PAD_NAME="10594 Pad pad"
#Use $CONNECTED to track tablet connected-ness

detect_tablet() {
	xsetwacom --list | grep "10594 Pen"
}

map_input() {
	#Mapping Pad buttons
	xsetwacom --set "$PAD_NAME" Button 1 "key +ctrl +z"
	xsetwacom --set "$PAD_NAME" Button 2 "key +e"
	xsetwacom --set "$PAD_NAME" Button 3 "key +b"

	# For some reason keys 4-7 don't exist. Don't question it.

	xsetwacom --set "$PAD_NAME" Button 8 "key +plus"
	xsetwacom --set "$PAD_NAME" Button 9 "key +minus"
	xsetwacom --set "$PAD_NAME" Button 10 "key +bracketright"
	xsetwacom --set "$PAD_NAME" Button 11 "key +bracketleft"
	xsetwacom --set "$PAD_NAME" Button 12 "key +space"

	ID_STYLUS=`xinput | grep "Pen stylus" | cut -f 2 | cut -c 4-5`

	xinput map-to-output $ID_STYLUS $MONITOR
}

notify() {
	local TITLE="Monoprice 10x6.25in Tablet Mapper Daemon"

	notify-send --icon="input-tablet" "$TITLE" "$1"
	echo "$1"

}

if [ "$1" = "--map-only" ]; then
	map_input
	exit
fi


# Loop
while true; do
	if [ ! "$CONNECTED" ]; then
		# Tablet not connected, check if present and map if so
		if [ "$(detect_tablet)" ]; then
			map_input
			CONNECTED="true"
			notify "Mapped to $MONITOR and mapped buttons!"
			logger -p daemon.info --tag "Monoprice 10594 Mapper Daemon" -- "Mapped Tablet to $MONITOR and mapped buttons"
		fi
	else
		# Tablet IS connected. Update status if not detected.
		if [ ! "$(detect_tablet)" ]; then
			unset CONNECTED
			notify "Tablet disconnected."
			logger -p daemon.info --tag "Monoprice 10594 Mapper Daemon" -- "Tablet was disconnected."
		fi
	fi

	sleep 1s
done
